apiVersion: v1
kind: Service
metadata:
  name: ads-b-service
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
    nodePort: 30000
  selector:
    app.kubernetes.io/name: ads-b-service
  type: NodePort

